# Setup
Installing needed libraries

In [1]:
! pip install numpy==1.26.4 scikit-learn==1.2.2 fastprogress==1.0.3 transformers==4.38.1 pandas==2.1.4 tqdm==4.66.1 torch==2.1.2 torchmetrics

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.1/131.1 kB 4.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 kB 3.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.5/8.5 MB 78.2 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 83.8 MB/s eta 0:00:00:00:010:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 kB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 76.6 MB/s eta 0:00:00:00:01
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.66.4
    Uninstalling tqdm-4.66.4:
      Successfully uninstalled tqdm-4.66.4
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.19.1
    Uninstalling tokenizers-0.19.1:
      Successfully uninstalled tokenizers-0.19.1
  Attempting uninstall: transfo

In [2]:
# optional
! pip install git+https://github.com/Haruray/ekphrasis-custom.git

  Cloning https://github.com/Haruray/ekphrasis-custom.git to /tmp/pip-req-build-_koevexq
  Running command git clone --filter=blob:none --quiet https://github.com/Haruray/ekphrasis-custom.git /tmp/pip-req-build-_koevexq
  Resolved https://github.com/Haruray/ekphrasis-custom.git to commit 33f15ce8eef096efe40b134aac0c06f437cd9a03
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 2.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.0/43.0 kB 1.9 MB/s eta 0:00:00
  Created wheel for ekphrasis: filename=ekphrasis-0.5.52-py3-none-any.whl size=617095 sha256=8369c674a0d03933a1f871f758c509c0ca7d3eb837ebeca444a180a1b4d6f0bc
  Stored in directory: /tmp/pip-ephem-wheel-cache-lwea23m2/wheels/db/aa/78/3324febc0249d71447c15e7cdf65517757e106402e6d6bb448
  Created wheel for mtranslate: filename=mtranslate-1.8-py3-none-any.whl size=3672 sha256=a57553a1d8c8e3b65649053ec8ab91745552395ae527693c879d4a08fe

In [3]:
import os

## Cloning Source Code Repository

In [4]:
%cd /kaggle/working/
if not os.path.isdir("TA-Multi-Label-Emotion-Classification-Indonesian-Text"):
  print("Cloning repo...")
  !git clone https://github.com/Haruray/TA-Multi-Label-Emotion-Classification-Indonesian-Text
%cd /kaggle/working/TA-Multi-Label-Emotion-Classification-Indonesian-Text
!git pull https://github.com/Haruray/TA-Multi-Label-Emotion-Classification-Indonesian-Text
    
%cd /kaggle/working/TA-Multi-Label-Emotion-Classification-Indonesian-Text/src

/kaggle/working
Cloning repo...
Cloning into 'TA-Multi-Label-Emotion-Classification-Indonesian-Text'...
remote: Enumerating objects: 52, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 52 (delta 13), reused 52 (delta 13), pack-reused 0
Unpacking objects: 100% (52/52), 199.51 KiB | 6.04 MiB/s, done.
/kaggle/working/TA-Multi-Label-Emotion-Classification-Indonesian-Text
From https://github.com/Haruray/TA-Multi-Label-Emotion-Classification-Indonesian-Text
 * branch            HEAD       -> FETCH_HEAD
Already up to date.
/kaggle/working/TA-Multi-Label-Emotion-Classification-Indonesian-Text/src


In [5]:
from MLEC import Trainer, SpanEmo, DataClass, EmoRec, EarlyStopping, EvaluateOnTest
from torch.utils.data import DataLoader
import torch
import datetime
import json
import numpy as np
import wandb
import shutil

In [6]:
seed = 42
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print("Currently using {}".format(device))

def set_seed(seed):    
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
set_seed(seed)

Currently using cuda:0


In [7]:
now = datetime.datetime.now()
filename = now.strftime("%Y-%m-%d %H-%M-%S")
# fw = open("../configs/" + filename + ".json", "a")
model_path = filename + ".pt"

## Constants

In [8]:
CHECKPOINT_PATH = model_path
MODEL_PATH = "/kaggle/working/TA-Multi-Label-Emotion-Classification-Indonesian-Text/models/"+filename+"_checkpoint.pt"
TRAIN_FILEPATH = "/kaggle/working/TA-Multi-Label-Emotion-Classification-Indonesian-Text/data/id_df_train_new.csv"
DEV_FILEPATH = "/kaggle/working/TA-Multi-Label-Emotion-Classification-Indonesian-Text/data/id_df_dev_new.csv"
TEST_FILEPATH = "/kaggle/working/TA-Multi-Label-Emotion-Classification-Indonesian-Text/data/id_df_test_new.csv"
MAX_LENGTH = 128
DROPOUT_RATE = 0.1
TOKENIZER_NAME = "indolem/indobert-base-uncased"
ENCODER_NAME = "indolem/indobert-base-uncased"

# === SPANEMO PARAMS ===
CLASSIFIER_LEARNING_RATE = 0.005
ENCODER_LEARNING_RATE = 2e-5
TRAIN_BATCH_SIZE = 16
EVAL_BATCH_SIZE = 16
LCA_LOSSES = [0.6]
ZLPR_LOSSES = [0.4]

# === INDOBERT PARAMS ===
# CLASSIFIER_LEARNING_RATE = 5e-5
# ENCODER_LEARNING_RATE = 5e-5
# TRAIN_BATCH_SIZE = 32
# EVAL_BATCH_SIZE = 32
# LCA_LOSSES = [0.9]
# ZLPR_LOSSES = [0.0]

MAX_EPOCH = 20
PATIENCE = 20
MODEL_TO_TRAIN = "spanemo" #  "emorec" or "spanemo"
USE_PREFIX = MODEL_TO_TRAIN == "spanemo" # only True if its SpanEmo
PROJECT_NAME = "TA Revisi" # wandb project name

LCA_LOSSES = [0.0, 0.6]
ZLPR_LOSSES = [0.0, 0.4]

os.environ["WANDB_API_KEY"] = "" # enter wandb api key here

# Dataset Processing

In [9]:
train_dataset = DataClass(
    filename=TRAIN_FILEPATH,
    max_length=MAX_LENGTH,
    tokenizer_name=TOKENIZER_NAME,
    use_prefix=USE_PREFIX
)
train_data_loader = DataLoader(train_dataset, batch_size=TRAIN_BATCH_SIZE, shuffle=True)

print("The number of training batches: ", len(train_data_loader))

dev_dataset = DataClass(
    filename=DEV_FILEPATH,
    max_length=MAX_LENGTH,
    tokenizer_name=TOKENIZER_NAME,
    use_prefix=USE_PREFIX
)
dev_data_loader = DataLoader(
    dev_dataset, batch_size=TRAIN_BATCH_SIZE, shuffle=False
)
print("The number of validation batches: ", len(dev_data_loader))
label_size = len(train_dataset.label_names)

test_dataset = DataClass(
    filename=TEST_FILEPATH,
    max_length=MAX_LENGTH,
    tokenizer_name=TOKENIZER_NAME,
    use_prefix=USE_PREFIX
)
test_data_loader = DataLoader(
    test_dataset, batch_size=EVAL_BATCH_SIZE, shuffle=False
)
print("The number of Test batches: ", len(test_data_loader))

/opt/conda/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.53k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/229k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

/opt/conda/lib/python3.10/site-packages/ekphrasis/classes/tokenizer.py:225: FutureWarning: Possible nested set at position 2190
  self.tok = re.compile(r"({})".format("|".join(pipeline)))


Word statistics files not found!
Downloading... done!
Unpacking... 

/opt/conda/lib/python3.10/site-packages/ekphrasis/classes/exmanager.py:14: FutureWarning: Possible nested set at position 42
  regexes = {k.lower(): re.compile(self.expressions[k]) for k, v in


done!
Reading corpus_id_web_wiki - 1grams ...
generating cache file for faster loading...
reading ngrams /root/.ekphrasis/stats/corpus_id_web_wiki/counts_1grams.txt
You can't omit/backoff and unpack hashtags!
 unpack_hashtags will be set to False


PreProcessing dataset ...: 100%|██████████| 1915/1915 [00:02<00:00, 790.21it/s]
/opt/conda/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


The number of training batches:  120
Reading corpus_id_web_wiki - 1grams ...
You can't omit/backoff and unpack hashtags!
 unpack_hashtags will be set to False


PreProcessing dataset ...: 100%|██████████| 525/525 [00:00<00:00, 782.21it/s]
/opt/conda/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


The number of validation batches:  33
Reading corpus_id_web_wiki - 1grams ...
You can't omit/backoff and unpack hashtags!
 unpack_hashtags will be set to False


PreProcessing dataset ...: 100%|██████████| 1079/1079 [00:01<00:00, 752.32it/s]


The number of Test batches:  68


# Training

In [10]:
#############################################################################
# Start Training
#############################################################################



test_results = {}
eval_results = {}

for lca, zlpr in zip(LCA_LOSSES, ZLPR_LOSSES):
    
    set_seed(seed)
    
    spanemo = SpanEmo(
        output_dropout=DROPOUT_RATE,
        lang="Indonesia",
        alpha=lca,
        beta=zlpr,
        embedding_vocab_size=len(train_dataset.tokenizer),
        device=device,
        encoder_name=ENCODER_NAME,
    )

    emorec = EmoRec(
        output_dropout=DROPOUT_RATE,
        lang="Indonesia",
        alpha=lca,
        beta=zlpr,
        embedding_vocab_size=len(train_dataset.tokenizer),
        label_size=len(train_dataset.label_names),
        device=device,
        encoder_name=ENCODER_NAME,
    )
    
    models = [spanemo, emorec]
    
    model = [x for x in models if x.name == MODEL_TO_TRAIN][0]

    run_name = f"{model.name}-roberta-BCE{str(1-lca-zlpr).replace('.','x')}-ZLPR{str(zlpr).replace('.','x')}-LCA{str(lca).replace('.','x')}"
    
    early_stopping = EarlyStopping(filename = filename, patience=PATIENCE, delta=0, criteria="f1_Macro", bigger_better=True)
    
    learn = Trainer(
        model,
        train_data_loader,
        dev_data_loader,
        filename=filename,
        col_names=train_dataset.label_names,
        early_stopping = early_stopping
    )
    
    learn.fit(
        classifier_learning_rate = CLASSIFIER_LEARNING_RATE,
        encoder_learning_rate = ENCODER_LEARNING_RATE,
        train_batch_size = TRAIN_BATCH_SIZE,
        max_epoch = MAX_EPOCH,
        project_name = PROJECT_NAME,
        run_name = run_name,
        device=device
    )
    
    evaluate = EvaluateOnTest(
        model, 
        test_data_loader, 
        model_path=MODEL_PATH, 
        col_names=train_dataset.label_names,
        run_name = "_test_"+run_name
    )
    evaluate_dev = EvaluateOnTest(
        model, 
        dev_data_loader, 
        model_path=MODEL_PATH, 
        col_names=train_dataset.label_names,
        run_name = "_dev_"+run_name
    )
    print("==========",run_name, "===========")
    
    test_results[run_name] = evaluate.predict(device=device)
    eval_results[run_name] = evaluate_dev.predict(device=device)
    
    wandb.finish()

/opt/conda/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


pytorch_model.bin:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

/opt/conda/lib/python3.10/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
wandb: Currently logged in as: syafiqfaray3. Use `wandb login --relogin` to force relogin


/opt/conda/lib/python3.10/site-packages/transformers/optimization.py:429: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


epoch#:  1
f1_Macro increased (inf --> 0.264485).  Saving model ...
epoch#:  2
f1_Macro increased (0.264485 --> 0.427058).  Saving model ...
epoch#:  3
f1_Macro increased (0.427058 --> 0.495564).  Saving model ...
epoch#:  4
f1_Macro increased (0.495564 --> 0.568970).  Saving model ...
epoch#:  5
f1_Macro increased (0.568970 --> 0.614977).  Saving model ...
epoch#:  6
f1_Macro increased (0.614977 --> 0.618538).  Saving model ...
epoch#:  7
EarlyStopping counter: 1 out of 20
epoch#:  8
f1_Macro increased (0.618538 --> 0.631235).  Saving model ...
epoch#:  9
f1_Macro increased (0.631235 --> 0.633558).  Saving model ...
epoch#:  10
EarlyStopping counter: 1 out of 20
epoch#:  11
EarlyStopping counter: 2 out of 20
epoch#:  12
EarlyStopping counter: 3 out of 20
epoch#:  13
EarlyStopping counter: 4 out of 20
epoch#:  14
EarlyStopping counter: 5 out of 20
epoch#:  15
EarlyStopping counter: 6 out of 20
epoch#:  16
EarlyStopping counter: 7 out of 20
epoch#:  17
EarlyStopping counter: 8 out of 20

F1-Macro: 0.6369 F1-Micro: 0.7246 Precision Macro: 0.6630 Recall Macro: 0.6252 JS-Macro: 0.4798 JS-Samples: 0.6425 MCC: 0.6637 Time: 00:28
Confusion Matrix:
[[[ 558   65]
  [  81  375]]

 [[ 978   17]
  [  51   33]]

 [[1016   23]
  [  17   23]]

 [[ 635   83]
  [ 109  252]]

 [[ 835   72]
  [  32  140]]

 [[1018   17]
  [  24   20]]

 [[ 765   72]
  [  92  150]]]


F1-Macro: 0.6336 F1-Micro: 0.7265 Precision Macro: 0.6526 Recall Macro: 0.6279 JS-Macro: 0.4776 JS-Samples: 0.6490 MCC: 0.6650 Time: 00:13
Confusion Matrix:
[[[262  35]
  [ 40 188]]

 [[476   9]
  [ 23  17]]

 [[491  13]
  [ 10  11]]

 [[311  38]
  [ 47 129]]

 [[413  31]
  [ 16  65]]

 [[491   8]
  [ 15  11]]

 [[372  49]
  [ 35  69]]]


/opt/conda/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


/opt/conda/lib/python3.10/site-packages/transformers/optimization.py:429: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


epoch#:  1
f1_Macro increased (inf --> 0.397491).  Saving model ...
epoch#:  2
EarlyStopping counter: 1 out of 20
epoch#:  3
f1_Macro increased (0.397491 --> 0.501696).  Saving model ...
epoch#:  4
f1_Macro increased (0.501696 --> 0.590312).  Saving model ...
epoch#:  5
f1_Macro increased (0.590312 --> 0.620592).  Saving model ...
epoch#:  6
f1_Macro increased (0.620592 --> 0.630581).  Saving model ...
epoch#:  7
EarlyStopping counter: 1 out of 20
epoch#:  8
EarlyStopping counter: 2 out of 20
epoch#:  9
f1_Macro increased (0.630581 --> 0.657106).  Saving model ...
epoch#:  10
EarlyStopping counter: 1 out of 20
epoch#:  11
EarlyStopping counter: 2 out of 20
epoch#:  12
EarlyStopping counter: 3 out of 20
epoch#:  13
EarlyStopping counter: 4 out of 20
epoch#:  14
EarlyStopping counter: 5 out of 20
epoch#:  15
f1_Macro increased (0.657106 --> 0.658791).  Saving model ...
epoch#:  16
EarlyStopping counter: 1 out of 20
epoch#:  17
EarlyStopping counter: 2 out of 20
epoch#:  18
EarlyStopping 

F1-Macro: 0.6532 F1-Micro: 0.7410 Precision Macro: 0.7151 Recall Macro: 0.6167 JS-Macro: 0.4964 JS-Samples: 0.6574 MCC: 0.6828 Time: 00:28
Confusion Matrix:
[[[ 541   82]
  [  69  387]]

 [[ 979   16]
  [  43   41]]

 [[1033    6]
  [  24   16]]

 [[ 608  110]
  [  73  288]]

 [[ 857   50]
  [  47  125]]

 [[1023   12]
  [  25   19]]

 [[ 767   70]
  [  91  151]]]


F1-Macro: 0.6588 F1-Micro: 0.7465 Precision Macro: 0.7276 Recall Macro: 0.6214 JS-Macro: 0.5074 JS-Samples: 0.6644 MCC: 0.6897 Time: 00:13
Confusion Matrix:
[[[256  41]
  [ 29 199]]

 [[477   8]
  [ 24  16]]

 [[501   3]
  [ 13   8]]

 [[299  50]
  [ 39 137]]

 [[432  12]
  [ 16  65]]

 [[494   5]
  [ 13  13]]

 [[373  48]
  [ 40  64]]]


In [11]:
import pickle 
with open(f'{model.name}_test.pkl', 'wb') as f:
    pickle.dump(test_results, f)
    
with open(f'{model.name}_eval.pkl', 'wb') as f:
    pickle.dump(eval_results, f)

In [12]:
evaluate = EvaluateOnTest(
        model, 
        test_data_loader, 
        model_path=MODEL_PATH, 
        col_names=train_dataset.label_names
    )
evaluate.predict(device=device)

F1-Macro: 0.6532 F1-Micro: 0.7410 Precision Macro: 0.7151 Recall Macro: 0.6167 JS-Macro: 0.4964 JS-Samples: 0.6574 MCC: 0.6828 Time: 00:28
Confusion Matrix:
[[[ 541   82]
  [  69  387]]

 [[ 979   16]
  [  43   41]]

 [[1033    6]
  [  24   16]]

 [[ 608  110]
  [  73  288]]

 [[ 857   50]
  [  47  125]]

 [[1023   12]
  [  25   19]]

 [[ 767   70]
  [  91  151]]]


{'f1-macro': 0.6532478476681745,
 'f1-micro': 0.7409812409812411,
 'precision-macro': 0.7151136909564828,
 'recall-macro': 0.6167275274504304,
 'js-macro': 0.4964207209215874,
 'js-samples': 0.657398826073525,
 'mcc': 0.6828194856643677}